version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - www-data:/var/www
    depends_on:
      - php
    enviroment:
      # - VIRTUAL_HOST: db.uplift.company
      - VIRTUAL_HOST: db.uplift.local
  node:
    build: ./node
    image: node:12
    tty: true
    volumes:
      - ./node/app:/app
      ports:
      - 8081:3000
    enviroment:
      # - VIRTUAL_HOST: app.uplift.company
      - VIRTUAL_HOST: app.uplift.local
  static:
    image: nginx:latest
    ports:
      - 8082:8080
    volumes:
      - ./static/:/var/www/html
    enviroment:
      # - VIRTUAL_HOST: dashboard.uplift.company
      - VIRTUAL_HOST: dashboard.uplift.local

  php:
    build: ./php
    volumes:
      - www-data:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:  
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exment_database
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: exment_user
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db

# volumes を定義する
volumes:
  # volume の名前を指定
  # Exmentのインストールパス
  www-data:
    # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    #external: trues
  # mysql dbのインストールパス
  mysql-data: